### PR TITLE
add zsh-completion

### PR DESCRIPTION
**Pull request by rxwen**
- support tab-completion for process name
- support tab-completion for tag name
- support all arguments

### CODE REVIEW

**Comment by burntcookie90** [comment]
This seems like it should probably be a separate repo as a zsh plugin

**Comment by rxwen** [comment]
Since the bash completion is bundled in the repo, I think it might be helpful if zsh completion is included too.

**Comment by burntcookie90** [comment]
ah, true, disregard me then :)

**Comment by rxwen** [comment]
i'll also submit it to zsh-completions repo too.

**Comment by gustavovendramini** [comment]
Could someone explain how to add _pidcat in zsh (Oh My ZSH)?

**Comment by vanniktech** [comment]
I've tried adding it although it does not seem to work in my case. (Maybe I'm also doing something wrong).

in `.zshrc` I'm adding:

`fpath=(~/.zsh-completion $fpath)`

And I'm downloading the file into the directory:

```
mkdir .zsh-completion
cd .zsh-completion
curl https://raw.githubusercontent.com/JakeWharton/pidcat/master/zsh-completion/_pidcat > _pidcat
```

**Comment by njzhangyifei** [comment]
> I've tried adding it although it does not seem to work in my case. (Maybe I'm also doing something wrong).
> 
> in `.zshrc` I'm adding:
> 
> `fpath=(~/.zsh-completion $fpath)`
> 
> And I'm downloading the file into the directory:
> 
> ```
> mkdir .zsh-completion
> cd .zsh-completion
> curl https://raw.githubusercontent.com/JakeWharton/pidcat/master/zsh-completion/_pidcat > _pidcat
> ```

You probably didn't run `compinit` after fpath changed.

**Comment by vanniktech** [comment]
Still does not work.

```
fpath=($HOME/.pidcat/zsh-completion $fpath)
compinit
```

There are entries for `pidcat` in `$HOME/.zcompdump`:

```
'pidcat' '_pidcat'
autoload -Uz _pidcat
```

**Pull request merged**
