### PR TITLE
New option to show timestamp

### PR DESCRIPTION
**Pull request by ronshapiro**
`-t` will now output timestamps on the left, following the Logcat option `-v time`

### CODE REVIEW

**Comment by JakeWharton** [comment]
Showing the date is not useful. I might consider this if it was removed as it's the least ugly variant so far.

**Comment by ronshapiro** [comment]
Happy to do so if you'd like, just give me the green light since the merge conflicts from 12+ months ago don't look pretty so it will take at least a bit of time to get it mergeable

**Comment by dangercrow** [comment]
@ronshapiro Has this been closed due to inactivity?
I seem to end up Googling this issue every few weeks to see if anything has happened on it yet.
Are you planning on remaking a new pull request or...?

**Comment by ronshapiro** [comment]
I haven't thought about it in a few years and was closing open PRs. Happy to revive if it's desired, but figured it's probably no longer relevant

**Comment by dangercrow** [comment]
I think it could still be quite a useful feature - having to use both logcat and pidcat to get readable things *and* timestamps is quite a pain.

**Comment by fleytman** [comment]
@JakeWharton This feature is not useless. Many people need it. I am QA, I need to determine events from the logs and it is important to know when they happened. Now we have to use logcat in parallel with pidcat only for this function.

**Pull request closed without merging**
